### ISSUE TITLE
Exception thrown on format

### ISSUE THREAD

**Issue by C2N14** [jeapostrophe/racket-langserver#31] opened 2021-03-23 18:41 UTC
While trying to use `racket-langserver` on VSCode with Magic Racket, trying to format the document I stumbled upon this issue:

```
Caught exn in request "textDocument/formatting"
=: contract violation
expected: number?
given: #f
context...:
/home/<user>/.local/share/racket/8.0/pkgs/racket-langserver/text-document.rkt:325:0: indent-line!
/home/<user>/.local/share/racket/8.0/pkgs/racket-langserver/text-document.rkt:313:7: loop
/home/<user>/.local/share/racket/8.0/pkgs/racket-langserver/text-document.rkt:294:0: range-formatting!
/usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
/home/<user>/.local/share/racket/8.0/pkgs/racket-langserver/methods.rkt:26:0: process-message
/usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
/home/<user>/.local/share/racket/8.0/pkgs/racket-langserver/main.rkt:54:2: consume

[Error - 11:37:25 AM] Request textDocument/formatting failed.
Message: internal error in method "textDocument/formatting"
Code: -32603
```

**Comment by jeapostrophe** [comment] 2021-03-24 13:19
I just pushed a fix. Can you confirm that it works for you? If not, could you maybe send me a file that generates the error?

**Closed** 2021-03-24 13:18 UTC

**Comment by ryanslade** [comment] 2021-03-24 14:20
I'm seeing this issue too, how can I ensure I'm running the latest version? 

`raco pkg update racket-langserver` says there are no updates available.

**Comment by ryanslade** [comment] 2021-03-24 14:26
Looks like it hasn't been picked up by `raco` yet: 
https://pkgs.racket-lang.org/package/racket-langserver

**Comment by jeapostrophe** [comment] 2021-03-24 14:27
I scheduled a refresh. It may take a bit.

**Comment by ryanslade** [comment] 2021-03-24 14:47
Perfect, thanks.

I can confirm that it's updated and the issue is fixed 👍

**Comment by C2N14** [comment] 2021-03-24 15:08
Thank you, I can confirm this as well!
