### ISSUE TITLE
Exception when opening file: interval-map-set!: start is not strictly less than end

### ISSUE THREAD

**Issue by senshu** [jeapostrophe/racket-langserver#16] opened 2020-06-13 20:57 UTC
One Racket source file in my project is triggering the exception below.
It happens everytime I open the file, or another file that requires it, in an editor that uses the Racket language server.

[Follow this link to download the problematic source file](https://raw.githubusercontent.com/senshu/Racket-Tiny-HDL/master/tiny-hdl/tiny-hdl-syntax.rkt)

I have tried to isolate what is causing the issue without success so far.
It seems that removing random parts of the code makes the exception disappear.
But when I try to create a minimal example, I cannot reproduce the error.

Here is my setup:

* Racket 7.7 with a fresh install of racket-langserver (b283c2b)
* Ubuntu 20.04, 64-bit
* Atom 1.47.0 with atom-ide-racket 0.3.0
* VS Code 1.46.0 with magic-racket 0.5.6

Please tell me what additional information I can provide to help fix the issue.

```
interval-map-set!: start is not strictly less than end
  im: (make-interval-map '(((6 . 12) . #<set: (3466 . 3468) (1990 ....
  start: 642
  end: 642
  value: (set '(670 . 674))
  context...:
   /usr/share/racket/pkgs/data-lib/data/interval-map.rkt:99:0: interval-map-set!
   /home/guillaume/.racket/7.7/pkgs/racket-langserver/check-syntax.rkt:36:4: syncheck:add-arrow method in build-trace%
   /usr/share/racket/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:844:0: connect-identifier
   /usr/share/racket/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:708:6: for-loop
   /usr/share/racket/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:707:4: for-loop
   /usr/share/racket/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:701:2: for-loop
   /usr/share/racket/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:669:0: annotate-variables
   /usr/share/racket/pkgs/drracket-tool-lib/drracket/private/syncheck/traversals.rkt:47:10: expanded-expression
   .../more-scheme.rkt:261:28
   /home/guillaume/.racket/7.7/pkgs/racket-langserver/check-syntax.rkt:75:0: check-syntax
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /home/guillaume/.racket/7.7/pkgs/racket-langserver/text-document.rkt:86:0: did-open!
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:486:18
   [repeats 1 more time]
   /home/guillaume/.racket/7.7/pkgs/racket-langserver/main.rkt:54:2: consume
```

**Comment by jeapostrophe** [comment] 2020-06-14 00:37
Do you also get the error when opening it in DrRacket?

**Comment by senshu** [comment] 2020-06-14 09:12
No. The log pane in DrRacket does not show any exception.
Everything seems to work as expected.

**Comment by cfinegan** [comment] 2020-06-14 15:26
I've done some looking into this. It appears that the error is generated from the semicolon on line 29 of the example source you provided. For some reason, DrRacket is describing this symbol as having a zero range (start = `642`, end = `642`) in the source document. `interval-map` expects to use half-open intervals as keys, so this causes the exception that you are experiencing. 

I suspect this is some kind of bug with DrRacket, since as far as I can tell in all other cases, it uses the "1-past-the-end" position for `end`, and it doesn't do this for other symbols that are only 1 character long.

In the mean time, the best quick fixes I can think of are:
1) discard ranges that are of length zero (probably minimally painful if it's just semicolons from syntax classes)
2) assume that zero-length ranges are actually ranges of length 1, and infer the correct end position.

**Comment by senshu** [comment] 2020-06-14 19:30
> For some reason, DrRacket is describing this symbol as having a zero range

I suppose that the range does not represent the colon itself, but the "zero-length pattern variable id" before the colon.
So, in this case, it is actually a valid range of length zero.

**Comment by cfinegan** [comment] 2020-06-15 15:49
Hm, are "zero-length" variable ids a common pattern in Racket code? If they are, then maybe the right thing to do is infer that a zero-length range actually refers to the range corresponding with the *next* non-zero-length token in the source? Or maybe not, since that sounds complicated and error-prone, maybe conflicting with other edge-cases.

My instinct is that using `:` for type classes is clearly already some kind of special case in the language (I'm not aware of any other places where `e:expr`, for example, would be parsed as `e`, `:`, and `expr` separately), so I'm inclined to assume that the DrRacket editor is treating this as a special case where 1 character after the zero-length id is the valid range for highlighting that zero-length id. 

If someone more familiar with the internals of the language can correct me on this, then I'm open to revisiting this and coming up with a better solution, but for now I'm leaning towards patching the language server to treat zero-length ranges as length-1 ranges for now, so the highlighting works in the case we know about, and users don't have to deal with the language server rejecting files containing this pattern.

**Comment by senshu** [comment] 2020-06-15 16:10
> Hm, are "zero-length" variable ids a common pattern in Racket code?

I cannot really answer since I am not a Racket expert. My comment is based on my understanding of the [official documentation about syntax patterns](https://docs.racket-lang.org/syntax/stxparse-patterns.html) that contains this sentence:

> Note that an id of the form `:syntax-class-id` is legal; see the discussion of a `~var` form with a zero-length `pvar-id`.

And later:

> If `pvar-id` is the zero-length identifier (`||`), then `pvar-id` is not bound, but the nested attributes of `syntax-class-use` are bound without prefixes.

As I understand it, the syntax `:syntax-class-id` is equivalent to `(~var || syntax-class-id)` where `||` is the zero-length identifier.

**Comment by cfinegan** [comment] 2020-06-15 21:57
I just pushed a fix for this, can you confirm that the issue is resolved on your machine? It should show up as a highlight over the `:` now.

**Comment by senshu** [comment] 2020-06-16 07:19
> can you confirm that the issue is resolved on your machine?

Yes. It works as expected with atom-ide-racket so far. The character `:` is highlighted when there is no id before.
Thanks a lot.

**Comment by cfinegan** [comment] 2020-06-16 14:59
No problem! Sorry you had to modify your code to work around the issue.

I'm closing this issue for now, I'll reopen it if commit f15c014 is discovered later to behave differently from how DrRacket handles this in other kinds of edge cases.

**Closed by cfinegan** 2020-06-16 14:59 UTC
